### ISSUE TITLE
Streams are ignoring fillCache option

### ISSUE THREAD

**Issue by Nocory** [Level/subleveldown#56]
`fillCache: true` has no effect on the cache or memory usage, when reading data via `createReadStream` in a subleveldown database.

This can apparently be fixed by adding `xopts.fillCache = opts.fillCache` to the extend function in leveldown.js.
https://github.com/Level/subleveldown/blob/1469fafafbb5e641f01ef9dba2c5a287ba82ba19/leveldown.js#L122

After adding that line, extra memory was utilized according to the `cacheSize` specified in the options for the main level instance.
I didn't submit a pull request, since I am not familiar with the rest of the workings of that file, but that line seemed to do the trick here.

**Comment by vweevers** [comment]
Your solution sounds good! We'll gladly take a PR.

(at a later time, I think we should simplify the option handling so that it accepts any custom option)

**Comment by Nocory** [comment]
Ok, submitted a small PR #57
