### ISSUE TITLE
Adding _seek to SubIterator

### ISSUE THREAD

**Issue by MeirionHughes** [Level/subleveldown#65]
So I've been trying to add support for _seek on SubIterator. In principle the change is simply the added lines: 

```
SubIterator.prototype._seek = function (key) {
  this.iterator.seek(concat(this.prefix, key))
}
```
but this _never_ gets called. 

If I do: 
```js
    var db = levelup(memdown())
    var sub = subdb(db, 'sub')

    db.once('open', function () {
     var it = sub.iterator({ keyAsBuffer: false, valueAsBuffer: false })
   
     console.log(it)
```

I get... 

```
Iterator {
...
  it:
   SubIterator {
     iterator:
      MemIterator {
       ...

```

It seems clear `Iterator` is not calling `this.it.seek`, but I have no idea where this Iterator prototype is. Any ideas?

**Comment by vweevers** [comment]
That's because the iterator created with `sub.iterator()` is an `encoding-down` iterator which doesn't expose seek (yet).

**Comment by vweevers** [comment]
To be precise, it doesn't _forward_ it yet.

**Comment by MeirionHughes** [comment]
dam... I didn't bother to check there as it wasn't in my chain. cheers.

**Comment by MeirionHughes** [comment]
oh balls... I pushed to the wrong origin. will revert.
