### ISSUE TITLE
Disable `clear()`

### ISSUE THREAD

**Issue by vweevers** [Level/subleveldown#73]
At least until we can implement it for real. Background: https://github.com/Level/levelup/pull/669#issuecomment-529192961.

**Comment by vweevers** [comment]
Actually, maybe it already works, because the default implementation of `clear()` is iterator-based and `subleveldown` limits the range on iterators.

Let's write a test.

**Comment by vweevers** [comment]
Yup, works out of the friggin box :)

I will polish my test later and push it.

**Comment by MeirionHughes** [comment]
does this support clearing nested subs? if not is there a way to force it to do so?
