### ISSUE TITLE
Applies prefix twice on nested sublevel

### ISSUE THREAD

**Issue by vweevers** [Level/subleveldown#78]
Because the prefix is applied on open:

https://github.com/Level/subleveldown/blob/42eca3529bac10cdcec632e71ff9d85d775d6592/leveldown.js#L90-L93

So if you open, close and reopen, `self.prefix = subdb.prefix + self.prefix` happens twice.

There are more issues with the open logic (#60, #77), so let's refactor it a bit.

**Comment by MeirionHughes** [comment]
yeah I've got this too. 4.1.0 was fine, but on 4.1.1 I get prefix duplication. 

I'm trying to replicate it, but its proving troublesome if I straight up make the subs in the same function. In practice my code is creating subs "on the fly" then caching a helper class that manages the subdb.

**Comment by MeirionHughes** [comment]
I've managed to duplicate it: 

```ts
  let fooDb = sub(db, "foo");
  let barDb = sub(fooDb, "bar");
  let rayDb = sub(barDb, "ray"); 

  await fooDb.put("def", "one")
  await barDb.put("def", "two")

  await rayDb.put("123", "hello world");
  await rayDb.put("124", "hello world");
  await rayDb.put("125", "hello world");
```

results in: 

```
 !foo!!bar!def
 !foo!!foo!!bar!!ray!123
 !foo!!foo!!bar!!ray!124
 !foo!!foo!!bar!!ray!125
 !foo!def
```

**Comment by vweevers** [comment]
Although... wait. The issue you're describing is a separate one (not about _re-_ opening) that we might be able to fix on a shorter term.

**Comment by MeirionHughes** [comment]
I've already tried with: 

```ts
  let db = levelup(encoding(memdown()));

  await db.open();

  let fooDb = sub(db, "foo");
  await fooDb.open();
  
  let barDb = sub(fooDb, "bar");
  await barDb.open();

  let rayDb = sub(barDb, "ray"); 
  await rayDb.open();
```
and I get the same.

**Comment by vweevers** [comment]
> I was going to see what difference this really has on this 3-layer nesting.

That's been replaced in a later version

**Comment by vweevers** [comment]
OK, I'm able to reproduce your issue on master as well.

**Comment by vweevers** [comment]
Possible fix is to replace:

https://github.com/Level/subleveldown/blob/279ac439250e76e0ca7734221e089a6360655868/leveldown.js#L92

With:

```js
self.leveldown = subdb.leveldown
```

**Comment by MeirionHughes** [comment]
yeah that seems to do the trick

**Comment by vweevers** [comment]
We could release that fix as semver-patch, but consumers can in theory lose access to already stored data (with a double prefix)... does that make it a breaking change?

**Comment by vweevers** [comment]
4.1.4

**Comment by MeirionHughes** [comment]
cheers: looks like its working well and I have about five sub-levels too. Thanks for the quick fix.
