### ISSUE TITLE
Possible issue with buffer keys

### ISSUE THREAD

**Issue by tinchoz49** [Level/subleveldown#87]
Hi everyone, I've been experimenting with Buffer keys and I found that when I run the next code, the createReadStream gives me different results every time. 

It should return `result 10` every time but instead it gives randomly 10 or 6 or 7 (it depends of the crypto random buffer key generated).

```javascript
const crypto = require('crypto')
const memdown = require('memdown')
const sub = require('subleveldown')

const db = sub(memdown(), 'test', { keyEncoding: 'binary', valueEncoding: 'json' })

;(async () => {
  for (let i = 0; i < 10; i++) {
    await db.put(crypto.randomBytes(32), { test: 'test ' + i })
  }

  let i = 0
  for await (const item of db.createReadStream()) {
    console.log(item.key.toString('hex'), item)
    i++
  }
  console.log('result ' + i)
})()
```

It works using level directly:

```javascript
level(encode(memdown(), { keyEncoding: 'binary', valueEncoding: 'json' }))
```

**Comment by vweevers** [comment]
Try using `level-mem` (which wraps `memdown` in a `levelup` interface, which is what `subleveldown` expects) instead of `memdown`.

If that doesn't work, can you share the output of `npm ls memdown subleveldown level` (and any other module that might be relevant)?

**Comment by tinchoz49** [comment]
Indeed that was the problem. I should read better the documentation :(

> Split a levelup database into sublevels with their own keyspace, encoding and events.

Thanks for the quick response and sorry for taking your time on this.

**Comment by tinchoz49** [comment]
oh wrong test, still happening.

```
├── encoding-down@6.3.0
├─┬ level@6.0.0
│ └─┬ level-packager@5.1.1
│   └── encoding-down@6.3.0  deduped
├─┬ level-mem@5.0.1
│ └── memdown@5.1.0  deduped
├── memdown@5.1.0
└─┬ subleveldown@4.1.4
  └── encoding-down@6.3.0  deduped
```

**Comment by tinchoz49** [comment]
reproduce: https://repl.it/@tinchoz49/subleveltest

**Comment by vweevers** [comment]
Thanks for the repro! This requires a deeper dive, I'll try to get to that on Friday.

**Comment by vweevers** [comment]
The problem is that we iterate everything less than `prefix + '\xff'` which translates to e.g. `'!test!ÿ'` which excludes bytes above 195 (c3 in hex).

We should be iterating everything less than `concat(prefix, Buffer.from([255]))`.

**Comment by vweevers** [comment]
AFAICT we've had this bug since forever but that's theoretical; I tried testing 2.1.0 but didn't succeed installing that with ancient node 0.10 and npm. I find it hard to believe no one encountered it until now.

**Comment by vweevers** [comment]
Plan to fix it:

1. Short-term, detect the presence of `keyEncoding: 'binary'` in options and adjust the `lt` logic accordingly. Maybe also support custom encodings (when it's [an object with property `buffer: true`](https://github.com/Level/codec#encoding-format)) or add an option that forces the use of buffers. Ideally `subleveldown` should not know about `keyEncoding` though, so..
1. Long-term, once [manifests](https://github.com/Level/supports) are commonplace, check `db.supports.bufferKeys` and if so, always use buffers internally.

**Comment by tinchoz49** [comment]
:100: this
> Long-term, once manifests are commonplace, check db.supports.bufferKeys and if so, always use buffers internally.

**Comment by vweevers** [comment]
Went with a slightly different solution that also works for byte 255. See #88.
