### ISSUE TITLE
Decoder Err !

### ISSUE THREAD

**Issue by giveerr** [Level/subleveldown#92]
i have some code that uses multileveldown with charwise. when i try to keyStream in parent of db ( have created with subleveldown ) that cause err like this

`events.js:298
      throw er; // Unhandled 'error' event
      ^
Error [EncodingError]: no decoder for:"!users!!base!1"`

i want to handle the main data in the parent db not the subdb's is there any way to do it ?

**Comment by vweevers** [comment]
I suppose you could do `db.createKeyStream({ keyEncoding: 'utf8' })` and then parse the keys yourself: strip subleveldown's prefixes and do `charwise.decode(key)`.

**Comment by giveerr** [comment]
@vweevers 
that works but actualy i think its not the best way because it will read all of it. is there another way to do this ??

**Comment by vweevers** [comment]
It's hard to see what you want to achieve and why. If you're using sublevels and one of the sublevels has a special encoding, then you'll want to access the data via that sublevel. If that's not possible then I would ask, is using a sublevel the right choice?
