### ISSUE TITLE
Should the `createReadStream` method be scoped to the subs?

### ISSUE THREAD

**Issue by theprojectsomething** [Level/subleveldown#94]
The [readme](https://github.com/Level/subleveldown#usage) example explaining how sub dbs "are just regular levelup instances" is a bit ambiguous, in that it also seems to suggest that the `createReadStream` method is scoped to the sub:

> ```js
> var sub = require('subleveldown')
> var level = require('level')
> 
> var db = level('db')
> var example = sub(db, 'example')
> var nested = sub(example, 'nested')
> ```
> The example and nested db's are just regular levelup instances:
> 
> ```js
> example.put('hello', 'world', function () {
>   nested.put('hi', 'welt', function () {
>     // will print {key:'hello', value:'world'}
>     example.createReadStream().on('data', console.log)
>   })
> })
> ```

Except this doesn't appear to be the case. The above example actually prints:
```js
{ key: '!nested!hi', value: 'welt' }
{ key: 'hello', value: 'world' }
```

Is this intentional?

**Comment by vweevers** [comment]
Aye, `sub.createReadStream()` yields the entries of itself and any nested sublevels (because they are part of `sub`). Similar to how `db.createReadStream()` yields all entries.

**Comment by theprojectsomething** [comment]
Just my two cents but feels like this is the only feature that feels a bit cumbersome (but easy to work around!). Either way, IMO its worth updating the readme so the example shows the correct output, if only to save rookies like myself scratching a hole in their head. Happy to make a PR if that helps.

**Comment by vweevers** [comment]
> Either way, IMO its worth updating the readme so the example shows the correct output, if only to save rookies like myself scratching a hole in their head.

Agree!

> Happy to make a PR if that helps.

👍
